Working example on Mac and Linux
Fattorino/ImNodeFlow pull request #35
Opened 2024-09-04 12:56 UTC by pavanakumar

Thanks for the fantastic library. I have 

- added a working example with `CMakeList.txt` that automatically download the sources and setup the targets
- the example working on SDL2+OpenGL3 and template `CMakeLists.txt` is provided in `readme.txt` for other backends
- fixed warnings on unused variable in `src/imgui_bezier_math.inl`
- fixed warning on reordering of class member in `include/ImNodeFlow.h`
- removed `CMakeLists.txt` from root folder

2024-09-08 09:59 UTC, Fattorino commented
I'll be reviewing this in the following weeks as work at uni has me quite busy. Meanwhile thanks for the contribution

2025-04-19 13:19 UTC, AaronAppel commented
Thanks pavanakumar for sharing your example. It would be nice if the documentation.md had a sort of "quick start" section or example.md to reference how to integrate a simple demo/starting point into an app's main loop. And thank you for the awesome node editor, Fattorino 👍

2025-04-20 21:33 UTC, Fattorino commented
it's sad to leave this PR un-merged and not updating the project more often. I hope one day I'll be able to show some love to it again and fix up some left over things.
_(University is such a diva taking up all my time lol)_

2025-04-24 09:19 UTC, arabine commented
@Fattorino do you need some help to  manage this project?

2025-04-28 07:50 UTC, arabine commented
Ok here is the updated CMakeLists that fixes warnings and specify ImGui version.

```cmake
cmake_minimum_required(VERSION 3.14)
project(MyProject VERSION 1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)

set(IMGUI_DIR ${CMAKE_CURRENT_LIST_DIR}/includes/imgui)
set(IMNODEFLOW_DIR ${CMAKE_CURRENT_LIST_DIR}/..)

include(FetchContent)

# Spécifiez une version ou une étiquette (tag) pour ImGui
FetchContent_Declare(
    imgui
    GIT_REPOSITORY "https://github.com/ocornut/imgui.git"
    GIT_TAG "v1.91.6"  # Remplacez par la version souhaitée
    SOURCE_DIR ${IMGUI_DIR}
    GIT_SHALLOW TRUE  # Télécharge uniquement le commit spécifié sans l'historique complet
)

FetchContent_MakeAvailable(imgui)

list(APPEND imgui_sources
    ${IMGUI_DIR}/imgui.cpp
    ${IMGUI_DIR}/misc/cpp/imgui_stdlib.cpp
    ${IMGUI_DIR}/imgui_draw.cpp
    ${IMGUI_DIR}/imgui_tables.cpp
    ${IMGUI_DIR}/imgui_widgets.cpp
    ${IMGUI_DIR}/backends/imgui_impl_sdl2.cpp
    ${IMGUI_DIR}/backends/imgui_impl_opengl3.cpp
)

list(APPEND imnode_flow_sources
    ${IMNODEFLOW_DIR}/src/ImNodeFlow.cpp
)

add_executable(example example.cpp ${imgui_sources} ${imnode_flow_sources})
target_include_directories(example PRIVATE ${IMGUI_DIR} ${IMNODEFLOW_DIR}/include ${IMGUI_DIR}/backends)
target_compile_definitions(example PRIVATE IMGUI_DEFINE_MATH_OPERATORS)

if(CMAKE_SYSTEM_NAME MATCHES Emscripten)
    include(cmake/emscripten.cmake)
else()
    include(cmake/desktop.cmake)
endif()

```

2025-04-28 12:17 UTC, Fattorino commented
Is this cmake for the example?

2025-04-28 13:29 UTC, pavanakumar commented
This is a change set to the existing CMakeLists.txt for the example I created, have now merged the changes by @arabine and a fix to the window header

2025-04-28 13:43 UTC, arabine commented
Okay nice, go for merge on my side. (not tested ecmascripten).

2025-04-28 14:14 UTC, Fattorino requested changes
Everything looks good, I just left two comments on minor details

2025-04-28 14:14 UTC, Fattorino commented on readme.md
> -## Simple Node example
I would like to keep this to demonstrate quickly the syntax and how easy it is to use. And possibly have it quite at the top so it's easy to see.

2025-04-28 14:14 UTC, Fattorino commented on CMakeLists.txt
I like having a CMake file that gathers the files and sets up the target as a library. Removing this requires a fully manual setup. Can we find some middle ground?

2025-04-29 07:26 UTC, arabine commented on readme.md
> -## Simple Node example
+ please add a simple code to setup the edior/grid, it is really not clear even in the documentation. So that a user can copy paste both classes easily to test.

2025-04-29 07:27 UTC, arabine commented on CMakeLists.txt
Yes but please merge this for now so we can iterate on this with your idea.

2025-04-29 08:48 UTC, pavanakumar commented on readme.md
> -## Simple Node example
I have included this code in the readme now. The node editor setup with grid is shown in the example.hpp. Also annotated it with some comments.

2025-04-29 08:49 UTC, pavanakumar commented on CMakeLists.txt
You can revert back your old `find_package(imgui)` behaviour to use system Imgui by passing the `-DUSE_SYSTEM_IMGUI=ON` option while configuring. Check my latest push.

2025-04-30 06:17 UTC, merged

2025-04-30 06:24 UTC, Fattorino commented
@pavanakumar I was taling about the "global" CMake, not the example one. I don't like how, now, to use the library you have to manually add the .cpp file to the list of sources of the executable. I much prefer the use of add_subdirectory() and then linking.
But Im open to discuss to find the true best solution (Im far from a CMake expert), if you could please open an issue about it so not to discuss it here.